/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IframeRouteImport } from './routes/iframe'
import { Route as AuthenticationRouteImport } from './routes/_authentication'
import { Route as R403RouteImport } from './routes/403'
import { Route as IframeNameRouteImport } from './routes/iframe/$name'
import { Route as AuthenticationTableRouteImport } from './routes/_authentication/table'
import { Route as AuthenticationTabRouteImport } from './routes/_authentication/tab'
import { Route as AuthenticationDashboardRouteImport } from './routes/_authentication/dashboard'
import { Route as AuthenticationFormBasicFormRouteImport } from './routes/_authentication/form/basic-form'
import { Route as AuthenticationFormAdvancedFormRouteImport } from './routes/_authentication/form/advanced-form'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeRoute = IframeRouteImport.update({
  id: '/iframe',
  path: '/iframe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeNameRoute = IframeNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => IframeRoute,
} as any)
const AuthenticationTableRoute = AuthenticationTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationTabRoute = AuthenticationTabRouteImport.update({
  id: '/tab',
  path: '/tab',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationDashboardRoute = AuthenticationDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationFormBasicFormRoute =
  AuthenticationFormBasicFormRouteImport.update({
    id: '/form/basic-form',
    path: '/form/basic-form',
    getParentRoute: () => AuthenticationRoute,
  } as any)
const AuthenticationFormAdvancedFormRoute =
  AuthenticationFormAdvancedFormRouteImport.update({
    id: '/form/advanced-form',
    path: '/form/advanced-form',
    getParentRoute: () => AuthenticationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/iframe': typeof IframeRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticationDashboardRoute
  '/tab': typeof AuthenticationTabRoute
  '/table': typeof AuthenticationTableRoute
  '/iframe/$name': typeof IframeNameRoute
  '/form/advanced-form': typeof AuthenticationFormAdvancedFormRoute
  '/form/basic-form': typeof AuthenticationFormBasicFormRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/iframe': typeof IframeRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticationDashboardRoute
  '/tab': typeof AuthenticationTabRoute
  '/table': typeof AuthenticationTableRoute
  '/iframe/$name': typeof IframeNameRoute
  '/form/advanced-form': typeof AuthenticationFormAdvancedFormRoute
  '/form/basic-form': typeof AuthenticationFormBasicFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/iframe': typeof IframeRouteWithChildren
  '/login': typeof LoginRoute
  '/_authentication/dashboard': typeof AuthenticationDashboardRoute
  '/_authentication/tab': typeof AuthenticationTabRoute
  '/_authentication/table': typeof AuthenticationTableRoute
  '/iframe/$name': typeof IframeNameRoute
  '/_authentication/form/advanced-form': typeof AuthenticationFormAdvancedFormRoute
  '/_authentication/form/basic-form': typeof AuthenticationFormBasicFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/iframe'
    | '/login'
    | '/dashboard'
    | '/tab'
    | '/table'
    | '/iframe/$name'
    | '/form/advanced-form'
    | '/form/basic-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/iframe'
    | '/login'
    | '/dashboard'
    | '/tab'
    | '/table'
    | '/iframe/$name'
    | '/form/advanced-form'
    | '/form/basic-form'
  id:
    | '__root__'
    | '/403'
    | '/_authentication'
    | '/iframe'
    | '/login'
    | '/_authentication/dashboard'
    | '/_authentication/tab'
    | '/_authentication/table'
    | '/iframe/$name'
    | '/_authentication/form/advanced-form'
    | '/_authentication/form/basic-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  IframeRoute: typeof IframeRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe': {
      id: '/iframe'
      path: '/iframe'
      fullPath: '/iframe'
      preLoaderRoute: typeof IframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe/$name': {
      id: '/iframe/$name'
      path: '/$name'
      fullPath: '/iframe/$name'
      preLoaderRoute: typeof IframeNameRouteImport
      parentRoute: typeof IframeRoute
    }
    '/_authentication/table': {
      id: '/_authentication/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AuthenticationTableRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authentication/tab': {
      id: '/_authentication/tab'
      path: '/tab'
      fullPath: '/tab'
      preLoaderRoute: typeof AuthenticationTabRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authentication/dashboard': {
      id: '/_authentication/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticationDashboardRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authentication/form/basic-form': {
      id: '/_authentication/form/basic-form'
      path: '/form/basic-form'
      fullPath: '/form/basic-form'
      preLoaderRoute: typeof AuthenticationFormBasicFormRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authentication/form/advanced-form': {
      id: '/_authentication/form/advanced-form'
      path: '/form/advanced-form'
      fullPath: '/form/advanced-form'
      preLoaderRoute: typeof AuthenticationFormAdvancedFormRouteImport
      parentRoute: typeof AuthenticationRoute
    }
  }
}

interface AuthenticationRouteChildren {
  AuthenticationDashboardRoute: typeof AuthenticationDashboardRoute
  AuthenticationTabRoute: typeof AuthenticationTabRoute
  AuthenticationTableRoute: typeof AuthenticationTableRoute
  AuthenticationFormAdvancedFormRoute: typeof AuthenticationFormAdvancedFormRoute
  AuthenticationFormBasicFormRoute: typeof AuthenticationFormBasicFormRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationDashboardRoute: AuthenticationDashboardRoute,
  AuthenticationTabRoute: AuthenticationTabRoute,
  AuthenticationTableRoute: AuthenticationTableRoute,
  AuthenticationFormAdvancedFormRoute: AuthenticationFormAdvancedFormRoute,
  AuthenticationFormBasicFormRoute: AuthenticationFormBasicFormRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

interface IframeRouteChildren {
  IframeNameRoute: typeof IframeNameRoute
}

const IframeRouteChildren: IframeRouteChildren = {
  IframeNameRoute: IframeNameRoute,
}

const IframeRouteWithChildren =
  IframeRoute._addFileChildren(IframeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  IframeRoute: IframeRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
